export const fileTypes = [
    //"arena_boxes",
    "cardpack",
    //"core_assets",
    //"event",
    //"frog_crystal",
    //"guildwars",
    //"item",
    //"localizationpack",
    //"mappack",
    "portraitpack",
    //"pvp_bundle",
    //"raid",
    //"runepack",
    //"santaBundle",
    //"storepack",
];