name: Update images
on:
  push:
    branches: [ gh-pages ]
    # whenever card data is updated
    paths:
      - 'dist/data.min.js'
  workflow_dispatch:

jobs:
  update-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.push.head.ref }}
          token: ${{ secrets.BOT_TOKEN }}

      - name: Setup Python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Download Files
        uses: ./.github/actions/download-files
        with:
          working-directory: ${{ env.GITHUB_WORKSPACE }}
          spellstone-user: ${{ secrets.SPELLSTONE_USER }}
          spellstone-password: ${{ secrets.SPELLSTONE_PASSWORD }}
          spellstone-salt: ${{ secrets.SPELLSTONE_SALT }}

      - name: Extract Assets
        uses: ./.github/actions/extract-assets
        with:
          working-directory: ${{ env.GITHUB_WORKSPACE }}

      - name: Extract Images
        uses: ./.github/actions/extract-images
        with:
          working-directory: ${{ env.GITHUB_WORKSPACE }}

      - name: Resize Images
        uses: ./.github/actions/resize-images
        with:
          working-directory: ${{ env.GITHUB_WORKSPACE }}

      - name: Update Spritesheets
        uses: ./.github/actions/update-spritesheets
        with:
          working-directory: ${{ env.GITHUB_WORKSPACE }}

      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if [[ $(git status --porcelain) ]]; then echo "true"; else echo "false"; fi)" >> $GITHUB_OUTPUT

      - name: Setup Node version
        if: steps.git-check.outputs.modified == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Node dependencies
        if: steps.git-check.outputs.modified == 'true'
        run: npm ci

      - name: Bundle changes
        if: steps.git-check.outputs.modified == 'true'
        run: npm run grunt images

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Jon Senchyna'
          git config --global user.email 'TheSench@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "Auto-update of Spellstone Images"
          git push
